version: '3'
services:
  postgres:
    image: 'postgres:14'
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./ddl:/ddl
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./app:/app
      - ./test:/test
      - ./ddl:/ddl
      - ./testLogs:/logs
    depends_on:
      - 'postgres'
    environment:
      - NODE_ENV
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_HOST
      - TESTING_API_KEY
      